[package]
name = "davenda-tls"
version = "0.1.0"
edition = "2024"

[dependencies]
davenda-data = { path = "../davenda-data" }
davenda-config = { path = "../davenda-config" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls"] }
thiserror = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "time", "net"] }
