[workspace]
resolver = "3"
members = [
    "crates/davenda-a11y",
    "crates/davenda-app",
    "crates/davenda-admin",
    "crates/davenda-assets",
    "crates/davenda-auth",
    "crates/davenda-cache",
    "crates/davenda-cms",
    "crates/davenda-cli",
    "crates/davenda-commerce",
    "crates/davenda-config",
    "crates/davenda-core",
    "crates/davenda-data",
    "crates/davenda-events",
    "crates/davenda-i18n",
    "crates/davenda-jobs",
    "crates/davenda-media",
    "crates/davenda-memberships",
    "crates/davenda-observability",
    "crates/davenda-ops",
    "crates/davenda-runtime",
    "crates/davenda-seo",
    "crates/davenda-storage",
    "crates/davenda-template",
    "crates/davenda-tls",
    "crates/davenda-wasm",
    "crates/zanzibar",
]

[workspace.package]
edition = "2024"
version = "0.1.0"
rust-version = "1.85"

[workspace.dependencies]
zanzibar = { path = "crates/zanzibar" }
