[package]
name = "davenda-cli"
version = "0.1.0"
edition = "2024"
default-run = "platform"

[dependencies]
async-trait = "0.1"
davenda-admin = { path = "../davenda-admin" }
davenda-assets = { path = "../davenda-assets" }
davenda-auth = { path = "../davenda-auth" }
davenda-app = { path = "../davenda-app" }
davenda-core = { path = "../davenda-core" }
davenda-cms = { path = "../davenda-cms" }
davenda-commerce = { path = "../davenda-commerce" }
davenda-config = { path = "../davenda-config" }
davenda-data = { path = "../davenda-data" }
davenda-events = { path = "../davenda-events" }
davenda-import = { path = "../davenda-import" }
davenda-media = { path = "../davenda-media" }
davenda-memberships = { path = "../davenda-memberships" }
davenda-ops = { path = "../davenda-ops" }
davenda-report = { path = "../davenda-report" }
davenda-runtime = { path = "../davenda-runtime" }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["net", "rt", "rt-multi-thread"] }

[[bin]]
name = "platform"
path = "src/main.rs"
