[package]
name = "shoppr-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
coil.workspace = true
coil-app.workspace = true
coil-auth.workspace = true
coil-config.workspace = true
coil-customer-sdk.workspace = true
coil-data.workspace = true
coil-runtime.workspace = true
coil-wasm = "0.1.0"
hex = "0.4"
shoppr-backend = { path = "../shoppr-backend" }
shoppr-fission = { workspace = true, default-features = false }
serde.workspace = true
sha2 = "0.10"
sqlx.workspace = true
tokio.workspace = true
toml = "0.8"
wat = "1"

[dev-dependencies]
axum = "0.8"
