[package]
name = "coil-tls"
version = "0.1.1"
edition = "2024"

rust-version = "1.85"
license = "MIT"
repository = "https://github.com/coil-framework/coil"
homepage = "https://coil.rs"
documentation = "https://coil.rs/docs"
description = "TLS management primitives for the Coil framework."
readme = "README.md"
[dependencies]
aes-gcm = "0.10"
async-trait = "0.1"
coil-data = { version = "0.1.1", path = "../coil-data" }
coil-config = { version = "0.1.1", path = "../coil-config" }
lers = { version = "0.4.0", default-features = false, features = ["http-01", "dns-01-cloudflare", "tls-alpn-01"] }
openssl = "0.10"
rand = "0.8"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls"] }
thiserror = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "time", "net"] }
