[package]
name = "davenda-admin"
version = "0.1.0"
edition = "2024"

[dependencies]
davenda-auth = { path = "../davenda-auth" }
davenda-core = { path = "../davenda-core" }
davenda-data = { path = "../davenda-data" }
davenda-jobs = { path = "../davenda-jobs" }
davenda-wasm = { path = "../davenda-wasm" }
