[package]
name = "davenda-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
davenda-auth = { path = "../davenda-auth" }
davenda-cache = { path = "../davenda-cache" }
davenda-config = { path = "../davenda-config" }
davenda-core = { path = "../davenda-core" }
davenda-wasm = { path = "../davenda-wasm" }
thiserror = "1.0"
