services:
  app:
    build:
      context: ../..
      dockerfile: apps/harbor-shop/Dockerfile.repo

  harbor-backend-example:
    build:
      context: ../..
      dockerfile: apps/harbor-shop/backend/harbor-loyalty-backend/Dockerfile.repo
