[package]
name = "harbor-shop-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
davenda-all.workspace = true
davenda-app.workspace = true
davenda-config.workspace = true
davenda-customer-sdk.workspace = true
davenda-data.workspace = true
davenda-runtime.workspace = true
harbor-shop-backend = { path = "../harbor-shop-backend" }
tokio.workspace = true
