[package]
name = "harbor-shop-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
davenda-all.workspace = true
davenda-app.workspace = true
davenda-auth.workspace = true
davenda-config.workspace = true
davenda-customer-sdk.workspace = true
davenda-data.workspace = true
davenda-runtime.workspace = true
davenda-wasm = "0.1.0"
hex = "0.4"
harbor-shop-backend = { path = "../harbor-shop-backend" }
serde.workspace = true
sha2 = "0.10"
tokio.workspace = true
toml = "0.8"
wat = "1"

[dev-dependencies]
axum = "0.8"
