[package]
name = "davenda-all"
version = "0.1.0"
edition = "2024"

[dependencies]
davenda-admin = { path = "../davenda-admin" }
davenda-app = { path = "../davenda-app" }
davenda-auth = { path = "../davenda-auth" }
davenda-cms = { path = "../davenda-cms" }
davenda-commerce = { path = "../davenda-commerce" }
davenda-config = { path = "../davenda-config" }
davenda-core = { path = "../davenda-core" }
davenda-customer-sdk = { path = "../davenda-customer-sdk" }
davenda-events = { path = "../davenda-events" }
davenda-media = { path = "../davenda-media" }
davenda-memberships = { path = "../davenda-memberships" }
davenda-ops = { path = "../davenda-ops" }
davenda-runtime = { path = "../davenda-runtime" }
thiserror = "1.0"
