[workspace]
resolver = "3"
members = [
    "crates/gitly-app",
    "crates/gitly-backend",
    "crates/gitly-bin",
]
default-members = ["crates/gitly-bin"]

[workspace.package]
edition = "2024"
version = "0.1.0"
rust-version = "1.85"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal"] }
davenda-admin = "0.1.0"
davenda-all = "0.1.0"
davenda-app = "0.1.0"
davenda-assets = "0.1.0"
davenda-auth = "0.1.0"
davenda-cms = "0.1.0"
davenda-config = "0.1.0"
davenda-core = "0.1.0"
davenda-customer-sdk = "0.1.0"
davenda-data = "0.1.0"
davenda-media = "0.1.0"
davenda-ops = "0.1.0"
davenda-runtime = "0.1.0"
davenda-wasm = "0.1.0"
