[package]
name = "coil-commerce"
version = "0.1.1"
edition = "2024"

rust-version = "1.85"
license = "MIT"
repository = "https://github.com/coil-framework/coil"
homepage = "https://coil.rs"
documentation = "https://coil.rs/docs"
description = "Commerce capabilities for the Coil framework."
readme = "README.md"
[dependencies]
coil-auth = { version = "0.1.1", path = "../coil-auth" }
coil-config = { version = "0.1.1", path = "../coil-config" }
coil-core = { version = "0.1.1", path = "../coil-core" }
coil-data = { version = "0.1.1", path = "../coil-data" }
coil-jobs = { version = "0.1.1", path = "../coil-jobs" }
toml = "0.8"
