[package]
name = "davenda-core"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
davenda-auth = { path = "../davenda-auth" }
davenda-cache = { path = "../davenda-cache" }
davenda-config = { path = "../davenda-config" }
davenda-template = { path = "../davenda-template" }
davenda-wasm = { path = "../davenda-wasm" }
hmac = "0.12"
rand = "0.8"
sha2 = "0.10"
thiserror = "1.0"
toml = "0.8"
