[package]
name = "gitly-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
coil.workspace = true
coil-app.workspace = true
coil-auth.workspace = true
coil-config.workspace = true
coil-core.workspace = true
coil-customer-sdk.workspace = true
coil-data.workspace = true
coil-runtime.workspace = true
coil-wasm.workspace = true
hex = "0.4"
gitly-backend = { path = "../gitly-backend" }
serde.workspace = true
sha2 = "0.10"
tokio.workspace = true
toml = "0.8"
wat = "1"

[dev-dependencies]
axum = "0.8"
