[package]
name = "shoppr"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
coil.workspace = true
shoppr-app = { path = "../shoppr-app" }
shoppr-backend = { path = "../shoppr-backend" }
serde.workspace = true
serde_json = "1"
tokio.workspace = true

[[bin]]
name = "shoppr"
path = "src/main.rs"
