[app]
name = "shoppr"
display_name = "Shoppr"

[domains]
canonical = "uk.localhost"
additional = ["www.localhost", "fr.localhost", "pl.localhost", "shop.example.com", "www.example.com"]

[i18n]
default_locale = "en-GB"
supported_locales = ["en-GB", "fr-FR", "pl-PL"]
localized_routes = true

[translations]

[[translations.catalogs]]
locale = "en-GB"
path = "translations/en-GB.toml"

[[translations.catalogs]]
locale = "fr-FR"
path = "translations/fr-FR.toml"

[[translations.catalogs]]
locale = "pl-PL"
path = "translations/pl-PL.toml"

[[sites]]
id = "shoppr-uk"
display_name = "Shoppr UK"
brand_name = "Shoppr"
canonical_domain = "uk.localhost"
additional_domains = ["www.localhost", "shop.example.com", "www.example.com"]
default_locale = "en-GB"
supported_locales = ["en-GB", "fr-FR", "pl-PL"]

[[sites]]
id = "shoppr-fr"
display_name = "Shoppr France"
brand_name = "Shoppr Paris"
canonical_domain = "fr.localhost"
additional_domains = ["fr-store.localhost"]
default_locale = "fr-FR"
supported_locales = ["en-GB", "fr-FR", "pl-PL"]

[[sites]]
id = "shoppr-pl"
display_name = "Shoppr Polska"
brand_name = "Shoppr Studio"
canonical_domain = "pl.localhost"
additional_domains = ["pl-store.localhost"]
default_locale = "pl-PL"
supported_locales = ["en-GB", "fr-FR", "pl-PL"]

[theme]
active = "harbor"
template_namespaces = ["customer-app", "harbor"]
asset_roots = ["theme/assets"]

[auth]
mode = "extend"
package = "shoppr-auth"

[modules]
enabled = ["cms", "media", "commerce", "commerce-payments-stripe", "memberships", "events", "admin", "ops"]

[[extensions]]
id = "shoppr-waitlist-tools"
package_version = "0.1.0"
artifact_sha256 = "86dd37605814d2e87a188d913eb4ec5741f85f21a6ebcced776d6d68bfd87c64"
customer_app_id = "shoppr"

[[extensions.handlers]]
id = "home.waitlist.banner"
grants = []

[[extensions]]
id = "shoppr-waitlist-ops-widget"
package_version = "0.1.0"
artifact_sha256 = "da915dc331157d559cd8c74b6fde674a4c65747653a0da90972bfabb9198b3c4"
customer_app_id = "shoppr"

[[extensions.handlers]]
id = "events.waitlist.summary"
grants = []
