[app]
name = "shoppr"
display_name = "Shoppr"

[domains]
canonical = "uk.127.0.0.1.nip.io"
additional = ["us.127.0.0.1.nip.io", "de.127.0.0.1.nip.io", "shop.example.com", "www.example.com"]

[i18n]
default_locale = "en-GB"
supported_locales = ["en-GB", "fr-FR", "de-DE", "en-US"]
localized_routes = true

[[sites]]
id = "harbor-uk"
display_name = "Shoppr UK"
brand_name = "Shoppr"
canonical_domain = "uk.127.0.0.1.nip.io"
additional_domains = ["shop.example.com", "www.example.com"]
default_locale = "en-GB"
supported_locales = ["en-GB", "fr-FR"]

[[sites]]
id = "harbor-us"
display_name = "Shoppr US"
brand_name = "Harbor Events"
canonical_domain = "us.127.0.0.1.nip.io"
additional_domains = ["us-store.127.0.0.1.nip.io"]
default_locale = "en-US"
supported_locales = ["en-US"]

[[sites]]
id = "harbor-de"
display_name = "Shoppr DE"
brand_name = "Harbor Europa"
canonical_domain = "de.127.0.0.1.nip.io"
additional_domains = ["de-store.127.0.0.1.nip.io"]
default_locale = "de-DE"
supported_locales = ["de-DE", "en-GB"]

[theme]
active = "harbor"
template_namespaces = ["customer-app", "harbor"]
asset_roots = ["theme/assets"]

[auth]
mode = "extend"
package = "shoppr-auth"

[modules]
enabled = ["cms", "media", "commerce", "commerce-payments-stripe", "memberships", "events", "admin", "ops"]

[[extensions]]
id = "shoppr-waitlist-tools"
package_version = "0.1.0"
artifact_sha256 = "a86d1a1646e818bf600653ba6cf3585162157517acf74d76c20ecba3328694dc"
customer_app_id = "shoppr"

[[extensions.handlers]]
id = "home.waitlist.banner"
grants = []
