[app]
name = "shoppr"
display_name = "Shoppr"

[domains]
canonical = "uk.127.0.0.1.nip.io"
additional = ["fr.127.0.0.1.nip.io", "pl.127.0.0.1.nip.io", "shop.example.com", "www.example.com"]

[i18n]
default_locale = "en-GB"
supported_locales = ["en-GB", "fr-FR", "pl-PL"]
localized_routes = true

[[sites]]
id = "shoppr-uk"
display_name = "Shoppr UK"
brand_name = "Shoppr"
canonical_domain = "uk.127.0.0.1.nip.io"
additional_domains = ["shop.example.com", "www.example.com"]
default_locale = "en-GB"
supported_locales = ["en-GB", "fr-FR", "pl-PL"]

[[sites]]
id = "shoppr-fr"
display_name = "Shoppr France"
brand_name = "Shoppr Paris"
canonical_domain = "fr.127.0.0.1.nip.io"
additional_domains = ["fr-store.127.0.0.1.nip.io"]
default_locale = "fr-FR"
supported_locales = ["en-GB", "fr-FR", "pl-PL"]

[[sites]]
id = "shoppr-pl"
display_name = "Shoppr Polska"
brand_name = "Shoppr Studio"
canonical_domain = "pl.127.0.0.1.nip.io"
additional_domains = ["pl-store.127.0.0.1.nip.io"]
default_locale = "pl-PL"
supported_locales = ["en-GB", "fr-FR", "pl-PL"]

[theme]
active = "harbor"
template_namespaces = ["customer-app", "harbor"]
asset_roots = ["theme/assets"]

[auth]
mode = "extend"
package = "shoppr-auth"

[modules]
enabled = ["cms", "media", "commerce", "commerce-payments-stripe", "memberships", "events", "admin", "ops"]

[[extensions]]
id = "shoppr-waitlist-tools"
package_version = "0.1.0"
artifact_sha256 = "3ad7b44218d04a3eba602051cbcb991bdd1ab69fd55ad995cd688af26ca6d067"
customer_app_id = "shoppr"

[[extensions.handlers]]
id = "home.waitlist.banner"
grants = []
