[workspace]
resolver = "3"
members = [
    "crates/shoppr-app",
    "crates/shoppr-backend",
    "crates/shoppr-bin",
    "backend/shoppr-loyalty-backend",
]
default-members = ["crates/shoppr-bin"]

[workspace.package]
edition = "2024"
version = "0.1.0"
rust-version = "1.85"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal"] }
coil-admin = "0.1.0"
coil = { package = "coil-rs", version = "0.1.0" }
coil-app = "0.1.0"
coil-assets = "0.1.0"
coil-auth = "0.1.0"
coil-cms = "0.1.0"
coil-commerce = "0.1.0"
coil-config = "0.1.0"
coil-core = "0.1.0"
coil-customer-sdk = "0.1.0"
coil-data = "0.1.0"
coil-events = "0.1.0"
coil-media = "0.1.0"
coil-memberships = "0.1.0"
coil-ops = "0.1.0"
coil-runtime = "0.1.0"
