services:
  app:
    build:
      context: ../..
      dockerfile: apps/shoppr/Dockerfile.repo

  shoppr-backend-example:
    build:
      context: ../..
      dockerfile: apps/shoppr/backend/shoppr-loyalty-backend/Dockerfile.repo
