[package]
name = "davenda-app"
version = "0.1.0"
edition = "2024"

[dependencies]
davenda-auth = { path = "../davenda-auth" }
davenda-assets = { path = "../davenda-assets" }
davenda-cli = { path = "../davenda-cli" }
davenda-config = { path = "../davenda-config" }
davenda-core = { path = "../davenda-core" }
davenda-data = { path = "../davenda-data" }
davenda-i18n = { path = "../davenda-i18n" }
davenda-jobs = { path = "../davenda-jobs" }
davenda-report = { path = "../davenda-report" }
davenda-runtime = { path = "../davenda-runtime" }
davenda-template = { path = "../davenda-template" }
davenda-wasm = { path = "../davenda-wasm" }
thiserror = "2.0.17"

[dev-dependencies]
davenda-storage = { path = "../davenda-storage" }
tempfile = "3"
