[package]
name = "harbor-shop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
davenda-all.workspace = true
harbor-shop-app = { path = "../harbor-shop-app" }
harbor-shop-backend = { path = "../harbor-shop-backend" }
tokio.workspace = true

[[bin]]
name = "harbor-shop"
path = "src/main.rs"
